---
- name: Update package cache
  become: yes
  apt:
    update_cache: yes

- name: Install Kodi
  become: yes
  package:
    name:
      - kodi
      - kodi-eventclients-kodi-send
    state: present