    #autoexec service
    - name: Create autoexec service folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kodi/addons/service.autoexec/"
        state: directory
      register: autoexec_new_result
      become: yes

    - name: Copy autoexec addon service addon xml
      ansible.builtin.copy:
        src: 'cronxbmc/autoexec_addon.xml'
        dest: '{{ ansible_env.HOME }}/.kodi/addons/service.autoexec/addon.xml'
        force: yes
      become: yes
    - name: Copy autoexec.py file to addon
      ansible.builtin.copy:
        src: 'cronxbmc/autoexec_new_gen.py'
        dest: '{{ ansible_env.HOME }}/.kodi/addons/service.autoexec/autoexec.py'
        force: yes
      become : yes
    #cronxbmc service
    - name: Copy cronxbmc archive file
      copy:
        src: 'cronxbmc/{{ item }}'
        dest: '/tmp/{{ item }}'
        force: no 
      loop:
      - "{{ cronxbmc_addon_file }}"
      become : yes

    - name: Extract cronxbmc plugin #because busy box
      shell: "cd /tmp/;unzip -o {{ cronxbmc_addon_file }} -d {{ ansible_env.HOME }}/.kodi/addons/;rm /tmp/{{ cronxbmc_addon_file }}"
      become : yes

    - name: create directory with parent directories
      file:
        path: "{{ ansible_env.HOME }}/.kodi/userdata/addon_data/service.cronxbmc/"
        state: directory
      become : yes

    - name: Copy cron.xml file
      copy:
        src: 'cronxbmc/{{ item }}'
        dest: '{{ ansible_env.HOME }}/.kodi/userdata/addon_data/service.cronxbmc/{{ item }}'
        force: yes 
      loop:
      - cron.xml
      become : yes

    - name: Wait for server to restart
      reboot:
        reboot_timeout: 3600
      become: true

    - name: Wait until HTTP webserver UP and status is 401
      uri:
        url: 'http://127.0.0.1:8080/'
        return_content: yes
        validate_certs: no
        status_code:
          - 401
      until: uri_output.status == 401
      retries: 10 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
      delay: 5 # Every 5 seconds
      register: uri_output

    - name: Enable cronxbmc plugin for new version Coreelec
      ansible.builtin.shell: |
        sleep 5; kodi-send --action="Addons.SetAddonEnabled(service.cronxbmc,true)"

    - name: Enable autoexec plugin for new version Coreelec
      ansible.builtin.shell: |
        sleep 5; kodi-send --action="Addons.SetAddonEnabled(service.autoexec,true)"
